# Site wide configuration

title: Vitor Jorge
description: "A lightweight site starter for Jekyll"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //vitorjorge.github.io
#url: http://localhost:4000

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - pagination


# Site owner
owner:
  name: Vitor Jorge
  web: //vitorjorge.github.io
  email: vitorjorge17@hotmail.com
  twitter: serumser
  bio: "Front-end developer from Portugal! I love animations and working on details that matter"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: u/0/112148140026724549553
  #  ad-client: ca-pub-7328585512091257
  #  ad-slot: 3049671934
  disqus-shortname: serumsercode


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
